apiVersion: v1
kind: Service
metadata:
  name: my-pro-app-service
spec:
  selector:
    app: my-pro-app
  ports:
    - protocol: TCP
      port: 80          # Service ka port
      targetPort: 80     # Container ka port
  type: ClusterIP       # ArgoCD ke liye ClusterIP kaafi hai agar Ingress use kar rahe ho
